# -*- coding: utf-8 -*-
"""unbalanced_classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uy5fkPwoq4sY_C1FWsKfzwjuBHQDORSf
"""

import pandas as pd
from sklearn.utils import resample

def downsampling(set):
  """Downsampling the majority class until reaching the minority class"""
  # classes
  classes = set["class"].value_counts()
  # split by classes
  majority = set[set["class"] == 0]
  minority = set[set["class"] == 1]

  # select only 1000 data points
  majority_downsampled = resample(majority, replace = False, n_samples = classes[1])

  set = pd.concat([majority_downsampled, minority])

  return set